apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: imagecloud
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  JWT_SECRET: "imagecloud-super-secret-key-change-in-production-min-256-bits"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: imagecloud
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
